# Generated by Django 5.1.3 on 2025-01-08 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='Categorie')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='Plat')),
                ('noms', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('prix', models.IntegerField(default=1)),
                ('categorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Categorie', to='backend.categorie')),
            ],
        ),
    ]
